### ISSUE TITLE
Integrate with rust's tracing crate/ecosystem

### ISSUE THREAD

**Issue by danbruder** [newrelic/newrelic-telemetry-sdk-rust#61]
This is a feature request to create a [Subscriber](https://docs.rs/tracing/0.1.22/tracing/#in-executables) implementation to enable users of the [tracing](https://docs.rs/tracing/0.1.22/tracing/) crate to send their transaction data to New Relic.

Once this has been completed, this crate should be added to the [list of subscribers](https://docs.rs/tracing/0.1.22/tracing/#related-crates).

**Comment by joshuabenuck** [comment]
Hi @danbruder,

As the crate currently stands, it doesn't integrate with Rust's tracing crate ecosystem, but you are right that it would be a good fit for that ecosystem. Thanks for the suggestion!

If you don't object, I'll repurpose this issue to track the work needed to do that integration.

As an aside:
I noticed a reference to a `tracing-opentelemetry` crate. That may open up the possibility of you using the `tracing` crate API to send data to New Relic prior to this crate supporting it. The OpenTelemetry Collector (which the Rust OTel project looks to [support](https://crates.io/crates/opentelemetry-otlp)) has a [New Relic exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/newrelicexporter). Alternatively, New Relic can accept [Zipkin traces](https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api) (which also looks to be [supported](https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-zipkin) by the Rust OTel project).

**Comment by danbruder** [comment]
Thank you for pointing me to `tracing-opentelemetry` + NewRelic exporter, I'll take a look at using that. Feel free to re-purpose this issue as you said!

**Comment by PoiScript** [comment]
Hello everyone, I had created a project for integrate this sdk with tracing. Feel free to take a look and leave any suggestions! https://github.com/PoiScript/tracing-newrelic :)

Also, @joshuabenuck, do you have any plans for publishing this sdk to crates.io? `tracing-newrelic` cannot be published to crates.io since it depends on this.
