### ISSUE TITLE
Production Use

### ISSUE THREAD

**Issue by dotjon0** [newrelic/newrelic-telemetry-sdk-rust#76]
Afternoon, is this repo ready for production usage? We note the latest tag version is '[v0.1-alpha](https://github.com/newrelic/newrelic-telemetry-sdk-rust/releases/tag/v0.1-alpha)'

Thank you

**Comment by dotjon0** [comment]
> Edit: it does look like the [opentelemetry crate](https://github.com/open-telemetry/opentelemetry-rust) is actively developed. I am guessing that would be the recommended approach.
> 
> My guess is that the alpha tag indicates that this repo is not yet ready for production. It doesn't look like it's been actively developed in a while now. I'd love to hear from the maintainers if there is a plan to resurrect it or recommend alternatives.

last PR not raised by a bot looks like 2020...

**Comment by after-ephemera** [comment]
The main branch has regular commits, so I don't think PR timing is as relevant.

**Comment by dotjon0** [comment]
> The main branch has regular commits, so I don't think PR timing is as relevant.

the 'main' branch was last updated 2 years ago...

<img width="915" alt="Screenshot 2023-02-01 at 17 33 43" src="https://user-images.githubusercontent.com/108075644/216119132-651d7f82-79b7-4067-bd58-625f6457bc3c.png">

**Comment by dotjon0** [comment]
> opentelemetry crate

Ah yes, appologies, https://github.com/open-telemetry/opentelemetry-rust seems the way to go

**Comment by dotjon0** [comment]
@Ak-x any feedback as to why this issue was closed please? Any feedback to add to the comments above from new relic? If this repo is not for production usage why is it public under new relic's official repos?

**Comment by Ak-x** [comment]
Hello @dotjon0 , the team is archiving this repository shortly. If there is additional interest here we recommend connecting with new relic through the explorers hub: https://forum.newrelic.com/s/.
